### ISSUE TITLE
Add .nvmrc config file to manage node versions across projects

### ISSUE THREAD

**Issue by Bastou** [willybrauner/webpack-base#100]
The goal of this file is to register the current node version of the project and allow [nvm](https://github.com/nvm-sh/nvm) (node.js version manager) to use the corresponding node version when we install the project dependencies.

***.nvmrc*** content example: 
```
13.10.1
```
And in project directory just run: 
```
nvm use
```

It can also be automated: https://github.com/nvm-sh/nvm#bash

Discussion is open!

**Comment by willybrauner** [comment]
No need for this base because we gonna use docker in the future :)
