### ISSUE TITLE
Updates from N10

### ISSUE THREAD

**Issue by risq** [willybrauner/webpack-base#126]
- [ ] AppView : routeChangedHandler, routeNotFoundHandler, pageNotFoundHandler

- [ ] GlobalConfig

- [ ] LanguageService (#134)

- [x] main.ts : routerBaseURL + GlobalConfig.inject ... (#132)
- [ ] DataFetcher : url construction (remove double slash) à a jouter au starter grav

**Comment by willybrauner** [comment]
Spliter chaque tâche par tickets
