### ISSUE TITLE
Ajouter composant de base comme <Button /> avec cas d'utilisations

### ISSUE THREAD

**Issue by Bastou** [willybrauner/webpack-base#54]
Ajouter un composant de base pour avoir un exemple avec les différentes manières d'utiliser la stack : import, props, css modules, store ... etc.

**Comment by willybrauner** [comment]
J’ai ajouter du commentaire dans AppView.module.less

Pour le reste, c’est du React classique (sauf pour le page register qui est également documenté) 

Tu as eu des difficultés sur autre chose ?

**Comment by willybrauner** [comment]
@Bastou ? Je close ?
